#-----------------------------
# GitHub action --> Manually run a workflow
#
#-----------------------------
name:  GitHub action

on:
  push:
    branches:
    - main
  
jobs:

  my_job:
    name: e2e testing
    runs-on: windows-latest
    steps:
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
     
    - name: Install Dependencies
      run: npm i
    - name: Start testing
      run: npm run test
  
